[package]
name = "examples"
version = "0.1.0"
authors = [ "linderd@iinet.net.au" ]

[[bin]]
name = "main"

[[bin]]
name = "now"

[dependencies.uuid]
git = "https://github.com/rust-lang/uuid.git"
version = "0.0.2"

[dependencies.glob]
git = "https://github.com/rust-lang/glob.git"
version = "0.0.3"
