[package]
name = "examples"
version = "0.1.0"
authors = [ "linderd@iinet.net.au" ]

[[bin]]
name = "tests"
path = "src/bin.rs"

[dependencies.debugging]
git = "https://github.com/shadowmint/rust-debugging"
tag = "0.1.8"
